### ISSUE TITLE
Error: White Noise 

### ISSUE THREAD

**Issue by schantanu** [gtalarico/django-vue-template#1]
I have yet to understand what DjangoWhiteNoise does, but when I use the command `py manage.py runserver` without making any changes I get the following error.

```
C:\KBaseDjango>py manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
August 14, 2018 - 10:28:54
Django version 2.0.6, using settings 'backend.settings.dev'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper
 at 0x0000000004FDAC80>
Traceback (most recent call last):
  File "C:\Installs\Python\lib\site-packages\django\core\servers\basehttp.py", l
ine 44, in get_internal_wsgi_application
    return import_string(app_path)
  File "C:\Installs\Python\lib\site-packages\django\utils\module_loading.py", li
ne 17, in import_string
    module = import_module(module_path)
  File "C:\Installs\Python\lib\importlib\__init__.py", line 126, in import_modul
e
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\KBaseDjango\backend\wsgi.py", line 13, in <module>
    from whitenoise.django import DjangoWhiteNoise
  File "C:\Installs\Python\lib\site-packages\whitenoise\django.py", line 2, in <
module>
    '\n\n'
ImportError:

Your WhiteNoise configuration is incompatible with WhiteNoise v4.0
This can be fixed by following the upgrade instructions at:
http://whitenoise.evans.io/en/stable/changelog.html#v4-0



The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Installs\Python\lib\site-packages\django\utils\autoreload.py", line 2
25, in wrapper
    fn(*args, **kwargs)
  File "C:\Installs\Python\lib\site-packages\django\core\management\commands\run
server.py", line 140, in inner_run
    handler = self.get_handler(*args, **options)
  File "C:\Installs\Python\lib\site-packages\django\contrib\staticfiles\manageme
nt\commands\runserver.py", line 27, in get_handler
    handler = super().get_handler(*args, **options)
  File "C:\Installs\Python\lib\site-packages\django\core\management\commands\run
server.py", line 65, in get_handler
    return get_internal_wsgi_application()
  File "C:\Installs\Python\lib\site-packages\django\core\servers\basehttp.py", l
ine 49, in get_internal_wsgi_application
    ) from err
django.core.exceptions.ImproperlyConfigured: WSGI application 'backend.wsgi.appl
ication' could not be loaded; Error importing module.
```

I edited the `backend/settings/wsgi.py` file and commented out lines to remove references to White Noise as per the instructions in the [WhiteNoise documentation](http://whitenoise.evans.io/en/stable/changelog.html#v4-0) and everything seems to be running fine.

I am using Django 2.0.6

**Comment by gtalarico** [comment]
Thank of submitting this @Schantanu 

Looks like Whitenoise 4.0 which was released 4 days ago had some breaking changes.
[4.0 Release](https://github.com/evansd/whitenoise/releases/tag/v4.0)
[4.0 Notes Docs](http://whitenoise.evans.io/en/stable/changelog.html#v4-0)

I have locked Whitenoise to 4.0 and updated `wsgy.py` accordingly
