### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by InVinCiblezz** [gtalarico/django-vue-template#24]
```
xxxx-Pro:django-vue-template zz$ python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    ) from exc
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
```
I use Mac and something wrong.
Could u help me plz?

**Comment by gtalarico** [comment]
Sounds like you don't have Django installed.
Did you install the dependencies from the requirements file?

**Comment by InVinCiblezz** [comment]
I used Django in another project. 
And I install Django again in this project after your suggestion.
But the error looks like to be another one.
`Successfully installed django-2.2 pytz-2019.1 sqlparse-0.3.0
zhangzhendeMacBook-Pro:django-vue-template zz$ python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'whitenoise'`
Am I missing something? Thanks a lot!

**Comment by gtalarico** [comment]
Please read through the Readme instructions.
This project has many dependencies:
https://github.com/gtalarico/django-vue-template/blob/master/Pipfile

You will need to use pipenv to get the dependencies installed. Cmds are included in the readme
